[package]
name = "net-services"
version = "0.1.0"
edition = "2021"


[dependencies]
dotenv = "0.15" 
chrono = { version = "0.4.39", features = ["serde"] }
diesel = { version = "2.2.7", features = ["chrono", "postgres"] }
serde = { version = "1.0.217", features = ["derive"] }


