version: '3.8'

services:
  postgress:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admTest2015
      POSTGRES_DB: fiberprovider    
    
    